/* config_defaults.h - GENERATED by tools/gen_config_header.py.
 * Do not edit.  Edit ../../config.json and regenerate.
 *
 * source: config.json  sha256[:16] = a0114ebee872b351
 *
 * CF-1: the same numbers the control app reads, compiled in so the
 * firmware boots safe with the laptop switched off.
 */
#ifndef ROVER_CONFIG_DEFAULTS_H
#define ROVER_CONFIG_DEFAULTS_H

#define CFG_HASH "a0114ebee872b351"

#define CFG_PWM_FREQ             1000
#define CFG_MIN_DUTY_LEFT        320
#define CFG_MIN_DUTY_RIGHT       330
#define CFG_TRIM                 -0.03f
#define CFG_MAX_DUTY             650
#define CFG_MAX_DUTY_PER_TICK    40
#define CFG_STEPS_PER_DEGREE     11.4f
#define CFG_BACKLASH_STEPS       24
#define CFG_MAX_STEP_RATE        500
#define CFG_RANGE_STOP_MM        350
#define CFG_VBAT_MIN_MV          6600
#define CFG_TILT_MIN_DEG         -35.0f
#define CFG_TILT_MAX_DEG         35.0f
#define CFG_TILT_RELEASE_MS      200
#define CFG_WATCHDOG_MS          250

#endif /* ROVER_CONFIG_DEFAULTS_H */
