#!/usr/bin/env python3
"""Flash the tunables from config.json into the firmware's compiled-in defaults.

CF-1: config.json is read identically by the control app and flashed into the
firmware's defaults.  The firmware can still be re-tuned at runtime over the
wire, but it must boot with sane numbers even with the laptop switched off
(design rule 4: safety lives in firmware).

    python tools/gen_config_header.py

Writes firmware/main/config_defaults.h.  Run it after editing config.json and
before `idf.py build`; the Makefile target `make firmware-config` does both.
"""

from __future__ import annotations

import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]

# (C identifier, json path, C type).  Only values the firmware actually needs -
# gains that live purely in the decision layer stay on the laptop.
FIELDS = [
    ("CFG_PWM_FREQ",          ("hardware", "pwm_freq"),          "int"),
    ("CFG_MIN_DUTY_LEFT",     ("hardware", "min_duty_left"),     "int"),
    ("CFG_MIN_DUTY_RIGHT",    ("hardware", "min_duty_right"),    "int"),
    ("CFG_TRIM",              ("hardware", "trim"),              "float"),
    ("CFG_MAX_DUTY",          ("hardware", "max_duty"),          "int"),
    ("CFG_MAX_DUTY_PER_TICK", ("hardware", "max_duty_per_tick"), "int"),
    ("CFG_STEPS_PER_DEGREE",  ("hardware", "steps_per_degree"),  "float"),
    ("CFG_BACKLASH_STEPS",    ("hardware", "backlash_steps"),    "int"),
    ("CFG_MAX_STEP_RATE",     ("hardware", "max_step_rate"),     "int"),
    ("CFG_RANGE_STOP_MM",     ("hardware", "range_stop_mm"),     "int"),
    ("CFG_VBAT_MIN_MV",       ("hardware", "vbat_min_mv"),       "int"),
    ("CFG_TILT_MIN_DEG",      ("hardware", "tilt_min_deg"),      "float"),
    ("CFG_TILT_MAX_DEG",      ("hardware", "tilt_max_deg"),      "float"),
    ("CFG_TILT_RELEASE_MS",   ("hardware", "tilt_release_ms"),   "int"),
    ("CFG_WATCHDOG_MS",       ("safety", "watchdog_ms"),         "int"),
]


def dig(cfg: dict, path: tuple[str, ...]):
    node = cfg
    for key in path:
        node = node[key]
    return node


def main() -> None:
    cfg_path = ROOT / "config.json"
    raw = cfg_path.read_bytes()
    cfg = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()[:16]

    lines = [
        "/* config_defaults.h - GENERATED by tools/gen_config_header.py.",
        " * Do not edit.  Edit ../../config.json and regenerate.",
        " *",
        f" * source: config.json  sha256[:16] = {digest}",
        " *",
        " * CF-1: the same numbers the control app reads, compiled in so the",
        " * firmware boots safe with the laptop switched off.",
        " */",
        "#ifndef ROVER_CONFIG_DEFAULTS_H",
        "#define ROVER_CONFIG_DEFAULTS_H",
        "",
        f'#define CFG_HASH "{digest}"',
        "",
    ]
    for name, path, ctype in FIELDS:
        value = dig(cfg, path)
        if ctype == "float":
            lines.append(f"#define {name:<24} {float(value)!r}f")
        else:
            lines.append(f"#define {name:<24} {int(value)}")
    lines += ["", "#endif /* ROVER_CONFIG_DEFAULTS_H */", ""]

    out = ROOT / "firmware" / "main" / "config_defaults.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} from config.json ({digest})")


if __name__ == "__main__":
    main()
